/**
 * Herbal Properties List
 * Complete list of medicinal properties for plant tagging
 * Extracted from properties.pdf
 * Primary language: English
 * Reference languages: Danish, French
 */

window.PROPERTIES_LIST = [
  "Adaptogens",
  "Aphrodisiac",
  "Aldose reductase inhibiting",
  "Analgesic",
  "Antiallergic",
  "Antibacterial",
  "Anticancer preventive",
  "Antidepressant",
  "Antiemetic",
  "Anti-inflammatory (general)",
  "Anti-inflammatory (musculoskeletal)",
  "Anti-inflammatory (brain)",
  "Anti-inflammatory (female reproductive)",
  "Anti-inflammatory (circulatory)",
  "Anti-inflammatory (liver)",
  "Anti-inflammatory (respiratory)",
  "Anti-inflammatory (digestive)",
  "Anti-inflammatory (topical)",
  "Anti-inflammatory (urinary)",
  "Anticoagulant",
  "Antimicrobial",
  "Antioxidant",
  "Antirheumatic",
  "Urinary antiseptic",
  "Antilithic",
  "Anti-ulcer",
  "Antiviral (internal)",
  "Antiviral (topical)",
  "Appetite stimulant",
  "Antiarrhythmic",
  "Astringent",
  "Metabolic stimulant",
  "Sedative",
  "Connective tissue strengthening",
  "Adrenal tonic",
  "Bitter tonic",
  "Vasodilator",
  "Blood purifying",
  "Blood sugar regulating",
  "Hemostatic",
  "Blood building",
  "Blood pressure regulating",
  "Hypertensive",
  "Hypotensive",
  "Bladder tonic",
  "Bronchial antispasmodic",
  "Warming",
  "Carminative",
  "Emollient",
  "Fibrinolytic",
  "Cholagogue",
  "Choleretic",
  "Vulnerary",
  "Cardioprotective",
  "Heart tonic",
  "Expectorant",
  "Hypnotic",
  "Immunosuppressive",
  "Immunomodulating",
  "Interferon promoting",
  "Antipruritic",
  "Cholesterol lowering",
  "Anticonvulsant",
  "Antispasmodic",
  "Circulatory stimulant",
  "Female tonic",
  "Laxative",
  "Hepatoprotective",
  "Liver cell regenerating",
  "Uterine relaxant",
  "Uterine contractor",
  "Uterine tonic",
  "Lymphatic stimulant",
  "Male tonic",
  "Menstrual regulator",
  "Galactagogue",
  "Antigalactagogue",
  "Nervine tonic",
  "Nootropic",
  "Kidney tonic",
  "Antiparasitic",
  "Progesterone effect",
  "Prolactin inhibiting",
  "Prostate growth inhibiting",
  "Mucous membrane strengthening",
  "Mucous membrane tonic",
  "Mucous reducing (lower respiratory)",
  "Mucous reducing (upper respiratory)",
  "Sialagogue",
  "Antifungal",
  "Diaphoretic",
  "Antiperspirant",
  "Antacid",
  "Tonic",
  "Diuretic",
  "Venotonic",
  "Weight reducing",
  "Estrogen regulating"
];

// Danish reference translations
window.PROPERTIES_DANISH = {
  "Adaptogens": "Adaptogener",
  "Aphrodisiac": "Afrodisiakum",
  "Aldose reductase inhibiting": "Aldosereduktase hæmmende",
  "Analgesic": "Analgetika / Smertestillende",
  "Antiallergic": "Antiallergiske",
  "Antibacterial": "Antibakterielle",
  "Anticancer preventive": "Anticancer-forebyggende",
  "Antidepressant": "Antidepressive",
  "Antiemetic": "Antiemetika",
  "Anti-inflammatory (general)": "Antiinflammatoriske (generelt)",
  "Anti-inflammatory (musculoskeletal)": "Antiinflammatoriske (bevægapparatet)",
  "Anti-inflammatory (brain)": "Antiinflammatoriske (hjerne)",
  "Anti-inflammatory (female reproductive)": "Antiinflammatoriske (kvindelige kønsorganer)",
  "Anti-inflammatory (circulatory)": "Antiinflammatoriske (kredsløb)",
  "Anti-inflammatory (liver)": "Antiinflammatoriske (lever)",
  "Anti-inflammatory (respiratory)": "Antiinflammatoriske (luftveje)",
  "Anti-inflammatory (digestive)": "Antiinflammatoriske (mave/tarm)",
  "Anti-inflammatory (topical)": "Antiinflammatoriske (udvortes)",
  "Anti-inflammatory (urinary)": "Antiinflammatoriske (urinveje)",
  "Anticoagulant": "Antikoagulerende",
  "Antimicrobial": "Antimikrobiske",
  "Antioxidant": "Antioxidante",
  "Antirheumatic": "Antireumatiske",
  "Urinary antiseptic": "Antiseptiske i urinvejene",
  "Antilithic": "Antilitiske",
  "Anti-ulcer": "Anti-ulcer",
  "Antiviral (internal)": "Antivirale (indvortes)",
  "Antiviral (topical)": "Antivirale (udvortes)",
  "Appetite stimulant": "Appetitstimulerende",
  "Antiarrhythmic": "Arytmimodvirkende",
  "Astringent": "Astringerende",
  "Metabolic stimulant": "Basalstofskiftet hæves",
  "Sedative": "Beroligende",
  "Connective tissue strengthening": "Bindevævsstyrkende",
  "Adrenal tonic": "Binyrebarktonic",
  "Bitter tonic": "Bitter tonics",
  "Vasodilator": "Blodkarudvidende",
  "Blood purifying": "Blodrensende",
  "Blood sugar regulating": "Blodsukkerregulerende",
  "Hemostatic": "Blodstillende",
  "Blood building": "Blodstyrkende",
  "Blood pressure regulating": "Blodtryksregulerende",
  "Hypertensive": "Blodtrykshævende",
  "Hypotensive": "Blodtrykssænkende",
  "Bladder tonic": "Blæretonics",
  "Bronchial antispasmodic": "Bronkie spasmolytiske",
  "Warming": "Brændende",
  "Carminative": "Carminative",
  "Emollient": "Emollierende",
  "Fibrinolytic": "Fibrinmodvirkende",
  "Cholagogue": "Galdedrivende",
  "Choleretic": "Galdestimulerende",
  "Vulnerary": "Helende",
  "Cardioprotective": "Hjertebeskyttende",
  "Heart tonic": "Hjertetonics",
  "Expectorant": "Hostemidler / Slimdrivende",
  "Hypnotic": "Hypnotiske",
  "Immunosuppressive": "Immunhæmmende",
  "Immunomodulating": "Immunregulerende",
  "Interferon promoting": "Interferon fremmende",
  "Antipruritic": "Kløestillende",
  "Cholesterol lowering": "Kolesterolnedsættende",
  "Anticonvulsant": "Krampeløsende (epilepsi)",
  "Antispasmodic": "Krampeløsnende",
  "Circulatory stimulant": "Kredsløbsstimulerende",
  "Female tonic": "Kvindetonics",
  "Laxative": "Laxative",
  "Hepatoprotective": "Leverbeskyttende",
  "Liver cell regenerating": "Levercellehelende",
  "Uterine relaxant": "Livmoderafslappende",
  "Uterine contractor": "Livmodersammentrækkende",
  "Uterine tonic": "Livmodertonics",
  "Lymphatic stimulant": "Lymfestimulerende",
  "Male tonic": "Mandetonics",
  "Menstrual regulator": "Menstruationsregulerende",
  "Galactagogue": "Mælkedrivende",
  "Antigalactagogue": "Mælkehæmmende",
  "Nervine tonic": "Nervetonic",
  "Nootropic": "Nootropiske",
  "Kidney tonic": "Nyretonic",
  "Antiparasitic": "Parasithæmmende",
  "Progesterone effect": "Progesteron effekt",
  "Prolactin inhibiting": "Prolaktinhæmmende",
  "Prostate growth inhibiting": "Prostata vækst-hæmmende",
  "Mucous membrane strengthening": "Slimhindestyrkende",
  "Mucous membrane tonic": "Slimhindetonic",
  "Mucous reducing (lower respiratory)": "Slimhæmmende (nedre luftveje)",
  "Mucous reducing (upper respiratory)": "Slimhæmmende (øvre luftveje)",
  "Sialagogue": "Spytdrivende",
  "Antifungal": "Svampehæmmende",
  "Diaphoretic": "Sveddrivende",
  "Antiperspirant": "Svedhæmmende",
  "Antacid": "Syredæmpende",
  "Tonic": "Tonics",
  "Diuretic": "Vanddrivende",
  "Venotonic": "Venestyrkende",
  "Weight reducing": "Vægtreducerende",
  "Estrogen regulating": "Østrogenregulerende"
};

// French reference translations
window.PROPERTIES_FRENCH = {
  "Adaptogens": "Adaptogènes",
  "Aphrodisiac": "Aphrodisiaque",
  "Aldose reductase inhibiting": "Inhibiteur d'aldose réductase",
  "Analgesic": "Analgésique",
  "Antiallergic": "Anti-allergique",
  "Antibacterial": "Antibactérien",
  "Anticancer preventive": "Anticancéreux préventif",
  "Antidepressant": "Antidépresseur",
  "Antiemetic": "Antiémétique",
  "Anti-inflammatory (general)": "Anti-inflammatoire (général)",
  "Anti-inflammatory (musculoskeletal)": "Anti-inflammatoire (musculo-squelettique)",
  "Anti-inflammatory (brain)": "Anti-inflammatoire (cerveau)",
  "Anti-inflammatory (female reproductive)": "Anti-inflammatoire (organes reproducteurs féminins)",
  "Anti-inflammatory (circulatory)": "Anti-inflammatoire (circulatoire)",
  "Anti-inflammatory (liver)": "Anti-inflammatoire (foie)",
  "Anti-inflammatory (respiratory)": "Anti-inflammatoire (respiratoire)",
  "Anti-inflammatory (digestive)": "Anti-inflammatoire (digestif)",
  "Anti-inflammatory (topical)": "Anti-inflammatoire (topique)",
  "Anti-inflammatory (urinary)": "Anti-inflammatoire (urinaire)",
  "Anticoagulant": "Anticoagulant",
  "Antimicrobial": "Antimicrobien",
  "Antioxidant": "Antioxydant",
  "Antirheumatic": "Antirhumatismal",
  "Urinary antiseptic": "Antiseptique urinaire",
  "Antilithic": "Antilithiasique",
  "Anti-ulcer": "Anti-ulcéreux",
  "Antiviral (internal)": "Antiviral (interne)",
  "Antiviral (topical)": "Antiviral (topique)",
  "Appetite stimulant": "Stimulant de l'appétit",
  "Antiarrhythmic": "Antiarythmique",
  "Astringent": "Astringent",
  "Metabolic stimulant": "Stimulant métabolique",
  "Sedative": "Sédatif",
  "Connective tissue strengthening": "Renforcement du tissu conjonctif",
  "Adrenal tonic": "Tonique surrénalien",
  "Bitter tonic": "Tonique amer",
  "Vasodilator": "Vasodilatateur",
  "Blood purifying": "Dépuratif sanguin",
  "Blood sugar regulating": "Régulateur de glycémie",
  "Hemostatic": "Hémostatique",
  "Blood building": "Hématopoïétique",
  "Blood pressure regulating": "Régulateur de tension artérielle",
  "Hypertensive": "Hypertenseur",
  "Hypotensive": "Hypotenseur",
  "Bladder tonic": "Tonique vésical",
  "Bronchial antispasmodic": "Antispasmodique bronchique",
  "Warming": "Réchauffant",
  "Carminative": "Carminatif",
  "Emollient": "Émollient",
  "Fibrinolytic": "Fibrinolytique",
  "Cholagogue": "Cholagogue",
  "Choleretic": "Cholérétique",
  "Vulnerary": "Vulnéraire",
  "Cardioprotective": "Cardioprotecteur",
  "Heart tonic": "Tonique cardiaque",
  "Expectorant": "Expectorant",
  "Hypnotic": "Hypnotique",
  "Immunosuppressive": "Immunosuppresseur",
  "Immunomodulating": "Immunomodulateur",
  "Interferon promoting": "Stimulant d'interféron",
  "Antipruritic": "Antiprurigineux",
  "Cholesterol lowering": "Hypocholestérolémiant",
  "Anticonvulsant": "Anticonvulsivant",
  "Antispasmodic": "Antispasmodique",
  "Circulatory stimulant": "Stimulant circulatoire",
  "Female tonic": "Tonique féminin",
  "Laxative": "Laxatif",
  "Hepatoprotective": "Hépatoprotecteur",
  "Liver cell regenerating": "Régénérateur hépatocellulaire",
  "Uterine relaxant": "Relaxant utérin",
  "Uterine contractor": "Contractant utérin",
  "Uterine tonic": "Tonique utérin",
  "Lymphatic stimulant": "Stimulant lymphatique",
  "Male tonic": "Tonique masculin",
  "Menstrual regulator": "Régulateur menstruel",
  "Galactagogue": "Galactagogue",
  "Antigalactagogue": "Antigalactagogue",
  "Nervine tonic": "Tonique nerveux",
  "Nootropic": "Nootropique",
  "Kidney tonic": "Tonique rénal",
  "Antiparasitic": "Antiparasitaire",
  "Progesterone effect": "Effet progestérone",
  "Prolactin inhibiting": "Inhibiteur de prolactine",
  "Prostate growth inhibiting": "Inhibiteur de croissance prostatique",
  "Mucous membrane strengthening": "Renforcement des muqueuses",
  "Mucous membrane tonic": "Tonique des muqueuses",
  "Mucous reducing (lower respiratory)": "Réducteur de mucus (voies respiratoires inférieures)",
  "Mucous reducing (upper respiratory)": "Réducteur de mucus (voies respiratoires supérieures)",
  "Sialagogue": "Sialagogue",
  "Antifungal": "Antifongique",
  "Diaphoretic": "Diaphorétique",
  "Antiperspirant": "Antiperspirant",
  "Antacid": "Antiacide",
  "Tonic": "Tonique",
  "Diuretic": "Diurétique",
  "Venotonic": "Veinotonique",
  "Weight reducing": "Amincissant",
  "Estrogen regulating": "Régulateur d'œstrogène"
};
